//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Source/Scripts/_GameFields/_InputSettings/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameFields.InputSettings
{
    public partial class @InputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""GameField"",
            ""id"": ""6c6eed05-6ffa-4e65-b6bc-70b9561e5217"",
            ""actions"": [
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""431a6c30-44d9-43d9-b9a3-a7f5bb0bcc6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Q"",
                    ""type"": ""Button"",
                    ""id"": ""606417e3-2289-4444-b323-35b538c505e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""54c3c7a3-1bba-4da1-8ecf-d87336de8cb8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftArrow"",
                    ""type"": ""Button"",
                    ""id"": ""c5a566ef-d891-4f13-91df-7acac95f26fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightArrow"",
                    ""type"": ""Button"",
                    ""id"": ""845c0fad-93a2-4339-b523-2797a4e54328"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownArrow"",
                    ""type"": ""Button"",
                    ""id"": ""4a4ed78c-b1c3-49b4-a097-18ffbef21c3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpArrow"",
                    ""type"": ""Button"",
                    ""id"": ""654a06e8-a2a6-48c9-92d5-d5ff13d92d7f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""78c1c15f-2f62-4051-8256-cafc4d235898"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3abdc8b8-684f-43be-b2d1-ea4d81e296e3"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""991f2ab5-9322-4239-ab95-08104c9cc290"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b661706-3ecd-4fe3-8371-6e1fff1787fd"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""LeftArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b89601a5-bd59-4038-9ae6-a4ba08d6b4f6"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RightArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c472217-43be-42f3-8236-24a012d41ec9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""DownArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6932da6-8509-46cb-be2d-e4e7d9a91794"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""UpArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // GameField
            m_GameField = asset.FindActionMap("GameField", throwIfNotFound: true);
            m_GameField_Enter = m_GameField.FindAction("Enter", throwIfNotFound: true);
            m_GameField_Q = m_GameField.FindAction("Q", throwIfNotFound: true);
            m_GameField_Esc = m_GameField.FindAction("Esc", throwIfNotFound: true);
            m_GameField_LeftArrow = m_GameField.FindAction("LeftArrow", throwIfNotFound: true);
            m_GameField_RightArrow = m_GameField.FindAction("RightArrow", throwIfNotFound: true);
            m_GameField_DownArrow = m_GameField.FindAction("DownArrow", throwIfNotFound: true);
            m_GameField_UpArrow = m_GameField.FindAction("UpArrow", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // GameField
        private readonly InputActionMap m_GameField;
        private List<IGameFieldActions> m_GameFieldActionsCallbackInterfaces = new List<IGameFieldActions>();
        private readonly InputAction m_GameField_Enter;
        private readonly InputAction m_GameField_Q;
        private readonly InputAction m_GameField_Esc;
        private readonly InputAction m_GameField_LeftArrow;
        private readonly InputAction m_GameField_RightArrow;
        private readonly InputAction m_GameField_DownArrow;
        private readonly InputAction m_GameField_UpArrow;
        public struct GameFieldActions
        {
            private @InputActions m_Wrapper;
            public GameFieldActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Enter => m_Wrapper.m_GameField_Enter;
            public InputAction @Q => m_Wrapper.m_GameField_Q;
            public InputAction @Esc => m_Wrapper.m_GameField_Esc;
            public InputAction @LeftArrow => m_Wrapper.m_GameField_LeftArrow;
            public InputAction @RightArrow => m_Wrapper.m_GameField_RightArrow;
            public InputAction @DownArrow => m_Wrapper.m_GameField_DownArrow;
            public InputAction @UpArrow => m_Wrapper.m_GameField_UpArrow;
            public InputActionMap Get() { return m_Wrapper.m_GameField; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GameFieldActions set) { return set.Get(); }
            public void AddCallbacks(IGameFieldActions instance)
            {
                if (instance == null || m_Wrapper.m_GameFieldActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_GameFieldActionsCallbackInterfaces.Add(instance);
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @Q.started += instance.OnQ;
                @Q.performed += instance.OnQ;
                @Q.canceled += instance.OnQ;
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
                @LeftArrow.started += instance.OnLeftArrow;
                @LeftArrow.performed += instance.OnLeftArrow;
                @LeftArrow.canceled += instance.OnLeftArrow;
                @RightArrow.started += instance.OnRightArrow;
                @RightArrow.performed += instance.OnRightArrow;
                @RightArrow.canceled += instance.OnRightArrow;
                @DownArrow.started += instance.OnDownArrow;
                @DownArrow.performed += instance.OnDownArrow;
                @DownArrow.canceled += instance.OnDownArrow;
                @UpArrow.started += instance.OnUpArrow;
                @UpArrow.performed += instance.OnUpArrow;
                @UpArrow.canceled += instance.OnUpArrow;
            }

            private void UnregisterCallbacks(IGameFieldActions instance)
            {
                @Enter.started -= instance.OnEnter;
                @Enter.performed -= instance.OnEnter;
                @Enter.canceled -= instance.OnEnter;
                @Q.started -= instance.OnQ;
                @Q.performed -= instance.OnQ;
                @Q.canceled -= instance.OnQ;
                @Esc.started -= instance.OnEsc;
                @Esc.performed -= instance.OnEsc;
                @Esc.canceled -= instance.OnEsc;
                @LeftArrow.started -= instance.OnLeftArrow;
                @LeftArrow.performed -= instance.OnLeftArrow;
                @LeftArrow.canceled -= instance.OnLeftArrow;
                @RightArrow.started -= instance.OnRightArrow;
                @RightArrow.performed -= instance.OnRightArrow;
                @RightArrow.canceled -= instance.OnRightArrow;
                @DownArrow.started -= instance.OnDownArrow;
                @DownArrow.performed -= instance.OnDownArrow;
                @DownArrow.canceled -= instance.OnDownArrow;
                @UpArrow.started -= instance.OnUpArrow;
                @UpArrow.performed -= instance.OnUpArrow;
                @UpArrow.canceled -= instance.OnUpArrow;
            }

            public void RemoveCallbacks(IGameFieldActions instance)
            {
                if (m_Wrapper.m_GameFieldActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IGameFieldActions instance)
            {
                foreach (var item in m_Wrapper.m_GameFieldActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_GameFieldActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public GameFieldActions @GameField => new GameFieldActions(this);
        private int m_KeyboardSchemeIndex = -1;
        public InputControlScheme KeyboardScheme
        {
            get
            {
                if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
                return asset.controlSchemes[m_KeyboardSchemeIndex];
            }
        }
        public interface IGameFieldActions
        {
            void OnEnter(InputAction.CallbackContext context);
            void OnQ(InputAction.CallbackContext context);
            void OnEsc(InputAction.CallbackContext context);
            void OnLeftArrow(InputAction.CallbackContext context);
            void OnRightArrow(InputAction.CallbackContext context);
            void OnDownArrow(InputAction.CallbackContext context);
            void OnUpArrow(InputAction.CallbackContext context);
        }
    }
}
