//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/Source/Scripts/_StartMenues/~InputSettings/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace StartMenues.InputSettings
{
    public partial class @InputActions: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""StartMenu"",
            ""id"": ""8dcbf2ce-5296-433f-9e0c-5fb7ae9cac91"",
            ""actions"": [
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""07c5431d-ed67-432c-87a6-7eb37fd968a6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownArrow"",
                    ""type"": ""Button"",
                    ""id"": ""116f5572-4a2d-4dcc-ab06-589dc500ea74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpArrow"",
                    ""type"": ""Button"",
                    ""id"": ""4bc53104-1216-4eb6-b0d1-a5c595d12dd6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""098d6cb2-44d2-404c-8bec-34773376a8b5"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f1534db-9d69-4e61-9df2-b263f534f863"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6345d43d-6642-4d76-808a-9bb7c3d3741f"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpArrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // StartMenu
            m_StartMenu = asset.FindActionMap("StartMenu", throwIfNotFound: true);
            m_StartMenu_Enter = m_StartMenu.FindAction("Enter", throwIfNotFound: true);
            m_StartMenu_DownArrow = m_StartMenu.FindAction("DownArrow", throwIfNotFound: true);
            m_StartMenu_UpArrow = m_StartMenu.FindAction("UpArrow", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // StartMenu
        private readonly InputActionMap m_StartMenu;
        private List<IStartMenuActions> m_StartMenuActionsCallbackInterfaces = new List<IStartMenuActions>();
        private readonly InputAction m_StartMenu_Enter;
        private readonly InputAction m_StartMenu_DownArrow;
        private readonly InputAction m_StartMenu_UpArrow;
        public struct StartMenuActions
        {
            private @InputActions m_Wrapper;
            public StartMenuActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @Enter => m_Wrapper.m_StartMenu_Enter;
            public InputAction @DownArrow => m_Wrapper.m_StartMenu_DownArrow;
            public InputAction @UpArrow => m_Wrapper.m_StartMenu_UpArrow;
            public InputActionMap Get() { return m_Wrapper.m_StartMenu; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(StartMenuActions set) { return set.Get(); }
            public void AddCallbacks(IStartMenuActions instance)
            {
                if (instance == null || m_Wrapper.m_StartMenuActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_StartMenuActionsCallbackInterfaces.Add(instance);
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
                @DownArrow.started += instance.OnDownArrow;
                @DownArrow.performed += instance.OnDownArrow;
                @DownArrow.canceled += instance.OnDownArrow;
                @UpArrow.started += instance.OnUpArrow;
                @UpArrow.performed += instance.OnUpArrow;
                @UpArrow.canceled += instance.OnUpArrow;
            }

            private void UnregisterCallbacks(IStartMenuActions instance)
            {
                @Enter.started -= instance.OnEnter;
                @Enter.performed -= instance.OnEnter;
                @Enter.canceled -= instance.OnEnter;
                @DownArrow.started -= instance.OnDownArrow;
                @DownArrow.performed -= instance.OnDownArrow;
                @DownArrow.canceled -= instance.OnDownArrow;
                @UpArrow.started -= instance.OnUpArrow;
                @UpArrow.performed -= instance.OnUpArrow;
                @UpArrow.canceled -= instance.OnUpArrow;
            }

            public void RemoveCallbacks(IStartMenuActions instance)
            {
                if (m_Wrapper.m_StartMenuActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IStartMenuActions instance)
            {
                foreach (var item in m_Wrapper.m_StartMenuActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_StartMenuActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public StartMenuActions @StartMenu => new StartMenuActions(this);
        public interface IStartMenuActions
        {
            void OnEnter(InputAction.CallbackContext context);
            void OnDownArrow(InputAction.CallbackContext context);
            void OnUpArrow(InputAction.CallbackContext context);
        }
    }
}
